"""Fix small issues in FIT files generated by Tymewear

Usage:
    python fitfix.py input.fit output.fit

Author: Dominik Rappaport
eMail: dominik@rappaport.at
Date: 30 Sep 2025
"""

import argparse
from fit_tool.fit_file import FitFile
from fit_tool.profile.messages.record_message import RecordMessage

def main():
    ap = argparse.ArgumentParser(description="Fix small issues in FIT files generated by Tymewear")
    ap.add_argument("input_fit")
    ap.add_argument("output_fit")
    args = ap.parse_args()

    fit = FitFile.from_file(args.input_fit)

    for record in fit.records:
        if isinstance(record.message, RecordMessage):
            record.message.power = record.message.developer_fields[16].get_value()
            record.message.cadence = min(record.message.cadence * 2, 254)

    fit.crc = None
    fit.to_file(args.output_fit)


if __name__ == "__main__":
    main()
